version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
    - name: sales
      identifier: raw_gz_sales
      # columns:
      #   - name: date_date
      #   - name: orders_id
      #   - name: pdt_id
      #   - name: revenue
      #   - name: quantity
    - name: product
      identifier: raw_gz_product
      # columns:
      #   - name: products_id
      #     tests:
      #       - unique
      #       - not_null
      #   - name: purchSE_PRICE
    - name: ship
      identifier: raw_gz_ship
      # columns:
      #   - name: orders_id
      #     tests:
      #       - unique
      #       - not_null
      #   - name: shipping_fee
      #   - name: logCost
      #   - name: ship_cost